# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    working_directory: ~/fe
    docker:
      - image: cimg/ruby:2.7.4-node
        environment:
          PGHOST: localhost
          PGUSER: user
          RAILS_ENV: test
      - image: postgres:14.4
        environment:
          POSTGRES_USER: user
          POSTGRES_DB: fe_test
          POSTGRES_PASSWORD:
    steps:
      - checkout
      - run:
          name: fe
          command: bundle -v
      - ruby/bundle-install

      - checkout
      - run: bundle install --path vendor/bundle
      - run: bundle exec rspec