default: &default
  adapter: postgresql
  encoding: unicode
  host: postgres
  username: user
  password: password
  pool: 5

development:
  <<: *default
  database: wetective_fe_development


test:
  <<: *default
  database: wetective_fe_test
